create table users(
      username varchar_ignorecase(50) not null primary key,
      password varchar_ignorecase(50) not null,
      enabled boolean not null);

  create table authorities (
      username varchar_ignorecase(50) not null,
      authority varchar_ignorecase(50) not null,
      constraint fk_authorities_users foreign key(username) references users(username));
      create unique index ix_auth_username on authorities (username,authority);

 create table account (id bigint generated by default as identity, nick varchar(255), password varchar(255), role varchar(255), username varchar(255), primary key (id));

 create table persistent_logins (
  username varchar_ignorecase(64) not null,
  series varchar_ignorecase(64) not null primary key,
  token varchar_ignorecase(64) not null,
  last_used timestamp not null);